### ISSUE TITLE
Can't install in HA 2023.1 (beta)

### ISSUE THREAD

**Issue by luca-angemi** [ldotlopez/ha-ideenergy#29]
Once I update to 2023.1 beta version I get the following in the logs when I restart:

![image](https://user-images.githubusercontent.com/9977955/209853205-b4d38dec-5837-443b-a7ea-2065cb05bf2d.png)

**Comment by hartmood** [comment]
Same here 
`Logger: homeassistant.util.package
Source: util/package.py:98 
First occurred: 13:50:12 (3 occurrences) 
Last logged: 13:50:28

Unable to install package ideenergy==1.0.0rc1: ERROR: Cannot install ideenergy==1.0.0rc1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip `

**Comment by ldotlopez** [comment]
@luca-angemi, @hartmood 

Can you test the git version of the integration?
Thanks

**Comment by hartmood** [comment]
Thanks very much. Done. But unfortunately with no success. 

`Logger: homeassistant.setup
Source: setup.py:202 
First occurred: 18:27:07 (1 occurrences) 
Last logged: 18:27:07

Setup failed for custom integration ideenergy: Requirements for ideenergy not found: ['ideenergy==1.0.0rc1']. `

**Comment by hartmood** [comment]
Logger: homeassistant.util.package
Source: util/package.py:98 
First occurred: 18:26:51 (3 occurrences) 
Last logged: 18:27:07

Unable to install package ideenergy==1.0.0rc1: ERROR: Cannot install ideenergy==1.0.0rc1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip

**Comment by luca-angemi** [comment]
Updated and tested. 

Works perfectly. 

Many thanks for your swift response.

**Comment by hartmood** [comment]
Strange. Any idea what‘s wrong with my setup?

**Comment by luca-angemi** [comment]
I just changed in my manifest.json the two characters mentioned in the change. 

rc1 --> rc2 
0a1 --> 0a2

**Comment by hartmood** [comment]
Thanks. That worked.

**Comment by ldotlopez** [comment]
You must use git version, I didn't publish a proper release with changes yet.
Instructions to use the git version varies from whatever installation method you used

**Comment by hartmood** [comment]
I just switched from openhab to HA so I am not that familiar with it. I see HACS and downloaded a new version and did a restart. That did not solve it. So I changed the json manually.
