### ISSUE TITLE
My last reading is from 9th of November 2024 7 am (Madrid)

### ISSUE THREAD

**Issue by hartmood** [ldotlopez/ha-ideenergy#76]
I haven't changed my configuration before, so is it just me or anyone else experiencing issues?

Core 2024.11.1
Supervisor 2024.11.3
Operating System 13.2
Frontend 20241106.2

i-DE Energy Monitor 2.1.2

**Comment by aitor422** [comment]
I am experiencing the same, so probably it is a general problem with I-de API

**Comment by Levante75** [comment]
Me too!

**Comment by jomavic** [comment]
Same here

**Comment by oscahie** [comment]
If you log-in to their web site there's a pop up stating there's some problem, try again later, etc. Hopefully they are aware of it :D

**Comment by hartmood** [comment]
I last emailed Iberdrola, and they fixed it. As far as I remember, @ldotlopez wasn't happy with my activity. @ldotlopez, is this still the case, and should we still be quiet?

**Comment by ad-ha** [comment]
> I last emailed Iberdrola, and they fixed it. As far as I remember, @ldotlopez wasn't happy with my activity. @ldotlopez, is this still the case, and should we still be quiet?

Hi @hartmood 

I would recommend you do not contact I-DE on this. They most probably will start looking into the API and try to find a way to block it. That's why I guess @ldotlopez made that comment before.

Also, I just tried to access the web and seems like they are now sending MFA code to the mobile phone. Tomorrow I will also have a better look on this... maybe the issue with the integration might be coming from this.

**Comment by oscahie** [comment]
I'm now getting readings again since around midnight so it was probably an outage?

**Comment by Levante75** [comment]
Me too, -:)

**Comment by hartmood** [comment]
API is back.

**Comment by oscahie** [comment]
Hmm is it down again? no readings for the last several hours for me 🤔

**Comment by Levante75** [comment]
Had readings, last one at 10-11 o'clock,
